name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Pull image from Docker Hub
      run: sudo docker pull doitformellc/ebh-website:latest

    - name: Delete old container
      run: sudo docker rm -f ebh-website-container || true  # Fixed typo here

    - name: Run Docker Container
      run: |
        sudo docker run -d -p 3000:3000 --name ebh-website-container \
           -e ACCESSKEY="${{ secrets.ACCESSKEY }}" \
           -e BUCKET="${{ secrets.BUCKET }}" \
           -e DATABASE="${{ secrets.DATABASE }}" \
           -e USER="${{ secrets.USER }}" \
           -e PASSWORD="${{ secrets.PASSWORD }}" \
           -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
           -e REGION="${{ secrets.REGION }}" \
           -e SECRETKEY="${{ secrets.SECRETKEY }}" \
           -e HOST="${{ secrets.HOST }}" \
           -e EMAIL_SMTP_HOST="${{ secrets.EMAIL_SMTP_HOST }}" \
           -e EMAIL_SMTP_PORT="${{ secrets.EMAIL_SMTP_PORT }}" \
           -e EMAIL_SMTP_SECURE="${{ secrets.EMAIL_SMTP_SECURE }}" \
           -e EMAIL_SMTP_REQUIRE_TLS="${{ secrets.EMAIL_SMTP_REQUIRE_TLS }}" \
           -e EMAIL_FROM="${{ secrets.EMAIL_FROM }}" \
           -e EMAIL_USER="${{ secrets.EMAIL_USER }}" \
           -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
           -e MAILGUN_API_KEY="${{ secrets.MAILGUN_API_KEY }}" \
           -e MAILGUN_DOMAIN="${{ secrets.MAILGUN_DOMAIN }}" \
           -e MAIL_FROM_EMAIL="${{ secrets.MAIL_FROM_EMAIL }}" \
           -e NEXT_PUBLIC_RECAPTCHA_SITE_KEY="${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" \
           -e RECAPTCHA_SECRET_KEY="${{ secrets.RECAPTCHA_SECRET_KEY }}" \
        doitformellc/ebh-website:latest
